<?php
/**
 * @var $block \Flashy\Integration\Block\Index
 */
?>
<?php if( $block->getFlashyId() && !($block->getFlashyPurchase())) : ?>
    <script type="text/javascript">
        //<![CDATA[
        flashy('Purchase', <?php echo json_encode($block->getOrderDetails()); ?>);
        //]]>
    </script>
<?php endif; ?>

<?php if( $block->getFlashyId() ): ?>
	<script type="text/javascript">
        //<![CDATA[
		flashy('amplify:Purchase', <?php echo json_encode($block->getOrderDetails()); ?>);
        //]]>
    </script>
<?php endif; ?>
